/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package anime;

import java.awt.event.KeyEvent;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.json.simple.JSONObject;

/**
 *
 * @author mtech
 */
public class mainviewanim extends javax.swing.JFrame {
heart h = new heart();
    /**
     * Creates new form main
     */
    static Long id;
    Long id1;
    Long id2;
    Long id3;
    Long id4;

    public mainviewanim() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        searchinp = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        movies = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1500, 960));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Search");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1080, 30, 120, 70);

        searchinp.setBackground(new java.awt.Color(0, 0, 0));
        searchinp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        searchinp.setForeground(new java.awt.Color(255, 255, 255));
        searchinp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        searchinp.setCaretColor(new java.awt.Color(255, 255, 255));
        searchinp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchinpKeyPressed(evt);
            }
        });
        getContentPane().add(searchinp);
        searchinp.setBounds(1200, 40, 260, 40);

        movies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "title", "gener", "directorname", "disc", "writer", "Likes", "year", "Duration"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        movies.setOpaque(false);
        movies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moviesMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                moviesMouseReleased(evt);
            }
        });
        movies.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                moviesKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(movies);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(580, 150, 860, 680);

        jLabel9.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Show all movies");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 90, 200, 70);

        welcome.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        welcome.setForeground(new java.awt.Color(255, 255, 255));
        welcome.setText("MOVIE ME");
        getContentPane().add(welcome);
        welcome.setBounds(40, 30, 530, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anime/Movies.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1500, 960);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static Long getid() {
        return id;
    }
    

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        /*
        Connection c = new Connection();
        c.get_pop();
        this.pop1.setIcon(new ImageIcon(c.pop1));
        this.pop2.setIcon(new ImageIcon(c.pop2));
        this.pop3.setIcon(new ImageIcon(c.pop3));
        this.pop4.setIcon(new ImageIcon(c.pop4));
        this.pop_text1.setText(String.valueOf(c.th1.get("romaji")));
        this.pop_text2.setText(String.valueOf(c.th2.get("romaji")));
        this.pop_text3.setText(String.valueOf(c.th3.get("romaji")));
        this.pop_text4.setText(String.valueOf(c.th4.get("romaji")));
        this.pop_text5.setText(String.valueOf(c.p1));
        this.pop_text6.setText(String.valueOf(c.p2));
        this.pop_text7.setText(String.valueOf(c.p3));
        this.pop_text8.setText(String.valueOf(c.p4));
        this.pop_text9.setText(String.valueOf(c.e1));
        this.pop_text10.setText(String.valueOf(c.e2));
        this.pop_text11.setText(String.valueOf(c.e3));
        this.pop_text12.setText(String.valueOf(c.e4));
        this.id1 = (Long) c.first.get("id");
        this.id2 = (Long) c.Second.get("id");
        this.id3 = (Long) c.third.get("id");
        this.id4 = (Long) c.forth.get("id");
        welcome.setText("Welcome to Move me " + h.name);
        */
    }//GEN-LAST:event_formWindowOpened
/*
    void showingui() {

        Connection c = new Connection();
        c.getanime(searchinp.getText());
        if (c.first != null) {
            this.pop1.setIcon(new ImageIcon(c.pop1));
            this.pop_text1.setText(String.valueOf(c.th1.get("romaji")));
            this.pop_text5.setText(String.valueOf(c.p1));
            this.pop_text12.setText(String.valueOf(c.e4));
            this.id1 = (Long) c.first.get("id");
        }
        if (c.Second != null) {
            this.pop2.setIcon(new ImageIcon(c.pop2));
            this.pop_text2.setText(String.valueOf(c.th2.get("romaji")));
            this.pop_text6.setText(String.valueOf(c.p2));
            this.pop_text10.setText(String.valueOf(c.e2));
            this.id2 = (Long) c.Second.get("id");
        }
        if (c.third != null) {

            this.pop3.setIcon(new ImageIcon(c.pop3));

            this.pop_text3.setText(String.valueOf(c.th3.get("romaji")));

            this.pop_text7.setText(String.valueOf(c.p3));

            this.pop_text11.setText(String.valueOf(c.e3));
            this.id3 = (Long) c.third.get("id");

        }
        if (c.forth != null) {
            this.pop4.setIcon(new ImageIcon(c.pop4));
            this.pop_text4.setText(String.valueOf(c.th4.get("romaji")));
            this.pop_text8.setText(String.valueOf(c.p4));
            this.pop_text12.setText(String.valueOf(c.e4));
            this.id4 = (Long) c.forth.get("id");
        }
        if (c.first == null) {
            JOptionPane.showMessageDialog(this, "We cant find the anime you are searching about D:");
        }
    }
    */
    private void searchinpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchinpKeyPressed
        // TODO add your handling code here:
        /*
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            showingui();

        }
*/
    }//GEN-LAST:event_searchinpKeyPressed
    public anime_view av = new anime_view();


    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
         welcome.setText("Welcome to Move me " + h.name);
    }//GEN-LAST:event_formWindowActivated

    private void moviesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moviesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_moviesMouseClicked

    private void moviesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moviesMouseReleased

    }//GEN-LAST:event_moviesMouseReleased

    private void moviesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_moviesKeyPressed
        // TODO add your handling code here:
        /*
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            int selectedRowIndex = movies.getSelectedRow();
            String id = movies.getValueAt(selectedRowIndex, 0).toString();
            deletemovie(id);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            System.out.println("From movies keypressed");
            int selectedRowIndex = movies.getSelectedRow();
            String id = movies.getValueAt(selectedRowIndex, 0).toString();
            saveChangesmovies(movies, id);
        }
        */
    }//GEN-LAST:event_moviesKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainviewanim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainviewanim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainviewanim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainviewanim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainviewanim().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable movies;
    private javax.swing.JTextField searchinp;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
